### PR TITLE
Update to VSCode syntax highlighter

### PR DESCRIPTION
**Pull request by DyBev**
Some changes to the VSCode syntax highlighter.

## [0.0.2]

- Changed the syntax blocks to allow for a more varied colour pallet
- Added embedding for CSS as long as it is between the <style> and </style> tags
- Changed the captures as textmate starts from 1 not 0 in indexes
- added some missing keywords
- added some missing captures
- added "in" to the signs captures to allow for cases such as "*for: item in array"
- .vsix file repackage

Images for reference, using the default colour scheme for VSC

_Old Syntax_
image

_Updated Syntax (This Pull request)_
image

### CODE REVIEW

**Comment by meatnordrink** [comment]
So excited to see this getting an update! :smile:

**Comment by jrc03c** [comment]
Yay! Updates! Quick question, though: Who's in charge of merging in PRs here? I can do it, but I don't want to step on anyone's toes.

**Comment by meatnordrink** [comment]
You and I are the only contributors so far, @jrc03c , and it definitely shouldn't be me...

**Comment by jrc03c** [comment]
@meatnordrink Sounds good! Thanks, @DyBev, for your contribution! I'll take a look at it soon!

**Comment by jrc03c** [comment]
Hey, @DyBev! This update looks really good! Thanks so much for submitting it! I only noticed two small things that might need fixing: Under the `*question` keyword, the `*save` and `*answers` sub-keywords seem to have lost their formatting. Here's a screenshot of what I mean:



Would you mind to fix those two little issues before I merge in your PR?

**Comment by DyBev** [comment]
Sorry didn't notice this I'll have a look at this today! to my knowledge I didn't touch anything with the #saveAnswer pattern but I'll take a look! @jrc03c

**Comment by DyBev** [comment]
Hey @jrc03c the fix has been pushed, feel free to take another look, I've also added in placeholder highlighting in the commit

**Comment by jrc03c** [comment]
Hey, @DyBev! Thanks for fixing those issues. I'm so glad this is getting an update! Thanks for your work on it!

By the way, if you don't mind my asking, how did you come across GuidedTrack? And what do you use it for?

**Comment by DyBev** [comment]
@jrc03c I'm part of the MindEase team, and we use it for the app

**Comment by jrc03c** [comment]
Oh, cool! We haven't interacted before through Spark Wave stuff, have we? If we have and I've forgotten, I apologize! 😅

**Comment by DyBev** [comment]
@jrc03c I don't believe so no

**Pull request merged**
